"""add_company_and_auth_to_users

Revision ID: 47dfa3c4365e
Revises: e9a1b3c5d7f2
Create Date: 2026-03-28 17:44:06.694044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47dfa3c4365e'
down_revision = 'e9a1b3c5d7f2'
branch_labels = None
depends_on = None


def upgrade():
    # companies table may already exist if db.create_all() ran before this migration
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    existing_user_cols = {c['name'] for c in inspector.get_columns('users')}
    existing_project_cols = {c['name'] for c in inspector.get_columns('projects')}

    if 'companies' not in existing_tables:
        op.create_table(
            'companies',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('slug', sa.String(length=255), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('slug'),
        )

    if 'company_id' not in existing_project_cols:
        with op.batch_alter_table('projects', schema=None) as batch_op:
            batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))

    cols_to_add = []
    if 'password_hash' not in existing_user_cols:
        cols_to_add.append(sa.Column('password_hash', sa.String(length=255), nullable=True))
    if 'company_id' not in existing_user_cols:
        cols_to_add.append(sa.Column('company_id', sa.Integer(), nullable=True))
    if 'role' not in existing_user_cols:
        cols_to_add.append(sa.Column('role', sa.String(length=50), nullable=True, server_default='admin'))

    if cols_to_add:
        with op.batch_alter_table('users', schema=None) as batch_op:
            for col in cols_to_add:
                batch_op.add_column(col)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role')
        batch_op.drop_column('company_id')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    op.drop_table('companies')
    # ### end Alembic commands ###
