"""add provider settings

Revision ID: 93bba3efba06
Revises: f1524feb239e
Create Date: 2026-03-27 10:07:22.382606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bba3efba06'
down_revision = 'f1524feb239e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('api_token', sa.Text(), nullable=True),
    sa.Column('default_location', sa.String(length=100), nullable=True),
    sa.Column('default_server_type', sa.String(length=100), nullable=True),
    sa.Column('default_image', sa.String(length=255), nullable=True),
    sa.Column('ssh_key_name', sa.String(length=255), nullable=True),
    sa.Column('ssh_public_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_settings')
    # ### end Alembic commands ###
